import { GoogleGenAI, Modality } from "@google/genai";

let currentTier: 'free' | 'paid' = 'free';

// Create an EventTarget that the UI can listen to for changes.
export const tierChangeNotifier = new EventTarget();
const tierChangeEvent = new Event('tierChange');

function setTier(newTier: 'free' | 'paid') {    
    if (currentTier !== newTier) {
        currentTier = newTier;
        tierChangeNotifier.dispatchEvent(tierChangeEvent);
    }
}

export const getCurrentTier = () => currentTier;

const getApiClient = (keyType: 'free' | 'paid'): GoogleGenAI => {
  const freeKey = process.env.API_KEY;
  const paidKey = process.env.API_KEY_PAID;
  let apiKeyToUse: string | undefined;

  if (keyType === 'paid') {
    if (!paidKey) {
      throw new Error("Attempted to use paid tier, but API_KEY_PAID is not set.");
    }
    apiKeyToUse = paidKey;
  } else { // free tier
    if (!freeKey) {
        throw new Error("API_KEY (free tier) environment variable not set.");
    }
    apiKeyToUse = freeKey;
  }
  
  return new GoogleGenAI({ apiKey: apiKeyToUse });
};

const handleApiError = (error: any, context: string): never => {
    console.error(`Error ${context}:`, error);
    if (error.message?.includes('quota')) {
        throw new Error("The service is currently at maximum capacity. Please try again in a few moments.");
    }
    if (error.message?.includes('API key not valid') || error.message?.includes('API key is invalid') || error.message?.includes('not found')) {
        throw new Error("An API key is invalid. Please check the application configuration.");
    }
    throw new Error(`Failed to ${context.toLowerCase()} due to an API error.`);
};

// --- Internal Generation Functions ---

const generateWithImagen = async (prompt: string): Promise<string> => {
    const ai = getApiClient('free');
    const enhancedPrompt = `${prompt}. Strict instruction: Generate a photorealistic, cinematic image in a 16:9 landscape aspect ratio.`;
    
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: enhancedPrompt,
        config: {
          numberOfImages: 1,
          aspectRatio: '16:9',
        },
    });

    const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
    if (!base64ImageBytes) {
        throw new Error("No image was generated by Imagen model.");
    }
    return `data:image/png;base64,${base64ImageBytes}`;
}

const generateWithGeminiFlash = async (prompt: string, keyType: 'free' | 'paid'): Promise<string> => {
  const ai = getApiClient(keyType);
  const enhancedPrompt = `${prompt}. Strict instruction: Generate a photorealistic, cinematic image in a 16:9 landscape aspect ratio.`;
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: { parts: [{ text: enhancedPrompt }] },
    config: { responseModalities: [Modality.IMAGE] },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }
  
  throw new Error("No image was generated by Gemini Flash model.");
};

// --- Exported Orchestration Functions ---

export const generateImage = async (prompt: string): Promise<string> => {
  // 1. Try Gemini Flash on Free Tier (Primary)
  try {
    console.log("Attempt 1: Gemini Flash model (free tier)");
    return await generateWithGeminiFlash(prompt, 'free');
  } catch (geminiFreeError: any) {
    console.warn("Primary model (Gemini Flash, free) failed. Reason:", geminiFreeError.message);
    // Proceed to fallback regardless of the error type.
  }

  // 2. Try Imagen on Free Tier (Fallback)
  try {
    console.log("Attempt 2: Imagen model (free tier)");
    return await generateWithImagen(prompt);
  } catch (imagenError: any) {
    console.warn("Fallback model (Imagen, free) failed. Reason:", imagenError.message);
    // Proceed to paid tier regardless of the error type.
  }
      
  // 3. Try Gemini Flash on Paid Tier
  if (process.env.API_KEY_PAID) {
    try {
      console.log("Attempt 3: Gemini Flash model (paid tier)");
      setTier('paid'); // Notify UI of tier change
      return await generateWithGeminiFlash(prompt, 'paid');
    } catch (geminiPaidError: any) {
      // If even the paid tier fails, throw a final error.
      return handleApiError(geminiPaidError, 'generate image (on paid tier)');
    }
  }

  // If we reach here, it means all free tiers failed and there was no paid key.
  const lastError = new Error("All free tiers failed and no paid API key is available.");
  return handleApiError(lastError, 'generate image');
};

const getBase64FromDataUrl = (dataUrl: string): string => dataUrl.split(',')[1];

const editImageInternal = async (base64ImageDataUrl: string, prompt: string, keyType: 'free' | 'paid'): Promise<string> => {
  const ai = getApiClient(keyType);
  const base64Data = getBase64FromDataUrl(base64ImageDataUrl);

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        { inlineData: { data: base64Data, mimeType: 'image/png' } },
        { text: prompt },
      ],
    },
    config: { responseModalities: [Modality.IMAGE] },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }
  
  throw new Error("No edited image was generated.");
};

export const editImage = async (base64ImageDataUrl: string, prompt: string): Promise<string> => {
    // 1. Try on Free Tier
    try {
        console.log("Attempt 1: Edit image (free tier)");
        return await editImageInternal(base64ImageDataUrl, prompt, 'free');
    } catch(freeError: any) {
        console.warn("Edit on free tier failed. Reason:", freeError.message);
        // Proceed to paid tier.
    }

    // 2. Try on Paid Tier
    if (process.env.API_KEY_PAID) {
        try {
            console.log("Attempt 2: Edit image (paid tier)");
            setTier('paid'); // Notify UI of tier change
            return await editImageInternal(base64ImageDataUrl, prompt, 'paid');
        } catch (paidError: any) {
            return handleApiError(paidError, 'edit image (on paid tier)');
        }
    }

    // If we reach here, free tier failed and no paid key exists.
    const lastError = new Error("Editing on free tier failed and no paid API key is available.");
    return handleApiError(lastError, 'edit image');
};