import { GoogleGenAI, Modality } from "@google/genai";

let currentTier: 'free' | 'paid' = 'free';

// Create an EventTarget that the UI can listen to for changes.
export const tierChangeNotifier = new EventTarget();
const tierChangeEvent = new Event('tierChange');

function setTier(newTier: 'free' | 'paid') {    
    if (currentTier !== newTier) {
        currentTier = newTier;
        tierChangeNotifier.dispatchEvent(tierChangeEvent);
    }
}

export const getCurrentTier = () => currentTier;

const getApiClient = (keyType: 'free' | 'paid'): GoogleGenAI => {
  const freeKey = process.env.API_KEY;
  const paidKey = process.env.API_KEY_PAID;
  let apiKeyToUse: string | undefined;

  if (keyType === 'paid') {
    if (!paidKey) {
      throw new Error("Attempted to use paid tier, but API_KEY_PAID is not set.");
    }
    apiKeyToUse = paidKey;
  } else { // free tier
    if (!freeKey) {
        throw new Error("API_KEY (free tier) environment variable not set.");
    }
    apiKeyToUse = freeKey;
  }
  
  return new GoogleGenAI({ apiKey: apiKeyToUse });
};

const handleApiError = (error: any, context: string): never => {
    console.error(`Error ${context}:`, error);
    if (error.message?.includes('quota')) {
        throw new Error("The service is currently at maximum capacity. Please try again in a few moments.");
    }
    if (error.message?.includes('API key not valid') || error.message?.includes('API key is invalid') || error.message?.includes('not found')) {
        throw new Error("An API key is invalid. Please check the application configuration.");
    }
    throw new Error(`Failed to ${context.toLowerCase()} due to an API error.`);
};

// --- Internal Generation Functions ---

const generateWithImagen = async (prompt: string): Promise<string> => {
    const ai = getApiClient('free');
    const enhancedPrompt = `${prompt}. Strict instruction: Generate a photorealistic, cinematic image in a 16:9 landscape aspect ratio.`;
    
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: enhancedPrompt,
        config: {
          numberOfImages: 1,
          aspectRatio: '16:9',
        },
    });

    const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
    if (!base64ImageBytes) {
        throw new Error("No image was generated by Imagen model.");
    }
    return `data:image/png;base64,${base64ImageBytes}`;
}

const generateWithGeminiFlash = async (prompt: string, keyType: 'free' | 'paid'): Promise<string> => {
  const ai = getApiClient(keyType);
  const enhancedPrompt = `${prompt}. Strict instruction: Generate a photorealistic, cinematic image in a 16:9 landscape aspect ratio.`;
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: { parts: [{ text: enhancedPrompt }] },
    config: { responseModalities: [Modality.IMAGE] },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }
  
  throw new Error("No image was generated by Gemini Flash model.");
};

// --- Exported Orchestration Functions ---

export const generateImage = async (prompt: string): Promise<string> => {
  // 1. Try Gemini Flash on Free Tier (Primary)
  try {
    console.log("Attempt 1: Gemini Flash model (free tier)");
    return await generateWithGeminiFlash(prompt, 'free');
  } catch (geminiFreeError: any) {
    // If primary fails for a non-quota reason, stop and report the error.
    if (!geminiFreeError.message?.includes('quota')) {
        return handleApiError(geminiFreeError, 'generate image (on primary model)');
    }
    
    console.warn("Gemini Flash free quota exceeded. Falling back to Imagen model.");

    // 2. Try Imagen on Free Tier (Fallback)
    try {
      console.log("Attempt 2: Imagen model (free tier)");
      return await generateWithImagen(prompt);
    } catch (imagenError: any) {
      console.warn("Imagen model (free fallback) failed. Reason:", imagenError.message);
      
      // ANY failure on the Imagen fallback (quota, regional error, etc.) triggers a move to the paid tier.
      if (!process.env.API_KEY_PAID) {
        console.error("Paid fallback failed: API_KEY_PAID is not configured.");
        return handleApiError(imagenError, 'generate image (all free tiers failed, paid fallback unavailable)');
      }
      
      // 3. Try Gemini Flash on Paid Tier
      try {
        console.log("Attempt 3: Gemini Flash model (paid tier)");
        setTier('paid'); // Notify UI of tier change
        return await generateWithGeminiFlash(prompt, 'paid');
      } catch (geminiPaidError: any) {
        return handleApiError(geminiPaidError, 'generate image (on paid tier)');
      }
    }
  }
};

const getBase64FromDataUrl = (dataUrl: string): string => dataUrl.split(',')[1];

const editImageInternal = async (base64ImageDataUrl: string, prompt: string, keyType: 'free' | 'paid'): Promise<string> => {
  const ai = getApiClient(keyType);
  const base64Data = getBase64FromDataUrl(base64ImageDataUrl);

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        { inlineData: { data: base64Data, mimeType: 'image/png' } },
        { text: prompt },
      ],
    },
    config: { responseModalities: [Modality.IMAGE] },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }
  
  throw new Error("No edited image was generated.");
};

export const editImage = async (base64ImageDataUrl: string, prompt: string): Promise<string> => {
    try {
        return await editImageInternal(base64ImageDataUrl, prompt, 'free');
    } catch(freeError: any) {
        if (freeError.message?.includes('quota')) {
            console.warn("Edit image free quota exceeded. Falling back to paid tier.");

            if (!process.env.API_KEY_PAID) {
                console.error("Paid fallback for edit failed: API_KEY_PAID is not configured.");
                return handleApiError(freeError, 'edit image (paid fallback unavailable)');
            }

            try {
                setTier('paid'); // Notify UI of tier change
                return await editImageInternal(base64ImageDataUrl, prompt, 'paid');
            } catch (paidError: any) {
                return handleApiError(paidError, 'edit image (on paid tier)');
            }
        } else {
            return handleApiError(freeError, 'edit image (on free tier)');
        }
    }
};